description: >
  yarn run build

executor: default

parameters:
  attach_at:
    description: where should we attach the workspace
    default: "."
    type: string
  cdk_directory:
    description: the directory where your cdk app resides
    type: string
    default: "."
  yarn_params:
    description: the parameters to pass the `yarn run build` command
    type: string
    default: ""

steps:
  - esbuild
  - yarn:
      yarn_command: run
      yarn_params: build << parameters.yarn_params >>
      yarn_directory: << parameters.cdk_directory >>
      attach_at: << parameters.attach_at >>
      persist: true
